import smtplib, logging, os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
from datetime import date
from apscheduler.schedulers.background import BackgroundScheduler
import database as db
import payroll as pl
import reports as rp

logger = logging.getLogger(__name__)
_scheduler = None


def send_daily_summary():
    """Send a daily attendance summary email at 9 PM."""
    try:
        sender     = db.get_setting('email_sender', '')
        password   = db.get_setting('email_password', '')
        recipients = db.get_setting('email_recipients', '')
        smtp_host  = db.get_setting('smtp_host', 'smtp.gmail.com')
        smtp_port  = int(db.get_setting('smtp_port', '587'))

        if not sender or not password or not recipients:
            logger.warning('Email not configured – skipping daily summary.')
            return

        company = db.get_setting('company_name', 'My Company')
        today   = date.today()
        ts      = today.strftime('%Y-%m-%d')

        conn = db.get_db()
        emps = db.rows_to_list(conn.execute('SELECT * FROM employees WHERE is_active=1 ORDER BY name').fetchall())
        conn.close()

        rows_html = ''
        reg = {"p": 0, "a": 0, "l": 0}
        for e in emps:
            s   = pl.get_live_status(e['id'], ts)
            dm  = int(s.get('debt_minutes', 0))
            col = {'green': '#10b981', 'amber': '#f59e0b', 'red': '#ef4444', 'blue': '#3b82f6'}.get(str(s.get('color')), '#64748b')
            h_worked: float = float(s.get('hours_worked') or 0.0)
            hw  = f"{h_worked:.1f}h" if s.get('clock_in') else '—'
            ci_val = s.get('clock_in')
            co_val = s.get('clock_out')
            ci  = str(ci_val).split('T')[-1].split('.')[0] if ci_val else '—'
            co  = str(co_val).split('T')[-1].split('.')[0] if co_val else '—'

            stat = str(s.get('status', 'absent'))
            if stat == 'present':
                if dm >= 0: reg["p"] = reg["p"] + 1
                else:       reg["l"] = reg["l"] + 1
            elif stat == 'absent':
                reg["a"] = reg["a"] + 1

            rows_html += f'''
            <tr>
              <td>{e["name"]}</td><td>{e["department"]}</td>
              <td>{ci}</td><td>{co}</td><td>{hw}</td>
              <td style="color:{col};font-weight:bold">{s["status"].replace("_"," ").title()}</td>
            </tr>'''

        html = f'''
<html><body style="font-family:Arial,sans-serif;background:#f8fafc;padding:20px">
  <div style="max-width:700px;margin:auto;background:white;border-radius:12px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,.08)">
    <div style="background:linear-gradient(135deg,#7c3aed,#06b6d4);padding:24px">
      <h2 style="color:white;margin:0">{company}</h2>
      <p style="color:rgba(255,255,255,.8);margin:4px 0 0">Daily Attendance Summary — {today.strftime("%A, %d %B %Y")}</p>
    </div>
    <div style="padding:20px">
      <div style="display:flex;gap:16px;margin-bottom:20px">
        <div style="flex:1;background:#ecfdf5;border-radius:8px;padding:12px;text-align:center">
          <div style="font-size:24px;font-weight:bold;color:#10b981">{reg['p']}</div>
          <div style="color:#64748b;font-size:12px">On Track</div>
        </div>
        <div style="flex:1;background:#fffbeb;border-radius:8px;padding:12px;text-align:center">
          <div style="font-size:24px;font-weight:bold;color:#f59e0b">{reg['l']}</div>
          <div style="color:#64748b;font-size:12px">Short Hours</div>
        </div>
        <div style="flex:1;background:#fef2f2;border-radius:8px;padding:12px;text-align:center">
          <div style="font-size:24px;font-weight:bold;color:#ef4444">{reg['a']}</div>
          <div style="color:#64748b;font-size:12px">Absent</div>
        </div>
      </div>
      <table width="100%" cellpadding="8" cellspacing="0" style="border-collapse:collapse;font-size:13px">
        <thead><tr style="background:#f1f5f9">
          <th align="left">Employee</th><th align="left">Dept</th>
          <th>Clock In</th><th>Clock Out</th><th>Hours</th><th>Status</th>
        </tr></thead>
        <tbody>{rows_html}</tbody>
      </table>
    </div>
    <div style="padding:12px 20px;background:#f8fafc;font-size:11px;color:#94a3b8;text-align:center">
      Auto-generated by Attendance System at 21:00
    </div>
  </div>
</body></html>'''

        msg = MIMEMultipart('mixed')
        msg['Subject'] = f'{company} — Daily Attendance Summary ({today.strftime("%d %b %Y")})'
        msg['From']    = sender
        msg['To']      = recipients

        # HTML Part
        msg.attach(MIMEText(html, 'html'))

        # Attachment Part (Daily Pulse PDF)
        try:
            pdf_path = rp.generate_daily_pulse()
            if pdf_path and os.path.exists(pdf_path):
                with open(pdf_path, 'rb') as f:
                    part = MIMEApplication(f.read(), Name=os.path.basename(pdf_path))
                part['Content-Disposition'] = f'attachment; filename="{os.path.basename(pdf_path)}"'
                msg.attach(part)
        except Exception as pdf_ex:
            logger.error(f"Could not generate/attach report: {pdf_ex}")

        # Send
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(sender, password)
            server.sendmail(sender, [r.strip() for r in recipients.split(',')], msg.as_string())

        logger.info('Daily summary email with attachment sent successfully.')

    except Exception as ex:
        logger.error(f'Failed to send daily summary: {ex}')


def setup_scheduler():
    global _scheduler
    if _scheduler and _scheduler.running:
        return _scheduler

    _scheduler = BackgroundScheduler(timezone='Asia/Karachi')
    # 9:00 PM daily summary
    _scheduler.add_job(send_daily_summary, 'cron', hour=21, minute=0, id='daily_summary')
    # Daily archive job at midnight
    _scheduler.add_job(
        lambda: __import__('database').archive_old_records(),
        'cron', hour=0, minute=5, id='archive_records'
    )
    _scheduler.start()
    logger.info('Scheduler started.')
    return _scheduler


def shutdown_scheduler():
    global _scheduler
    if _scheduler and _scheduler.running:
        _scheduler.shutdown(wait=False)
